enum Colors {
	COLOR_ANTELOPE = 16,
	COLOR_CYBER_SHEEP,
	COLOR_FOX,
	COLOR_HUMAN,
	COLOR_SHEEP,
	COLOR_TURTLE,
	COLOR_WOLF,
	COLOR_DANDELION,
	COLOR_GRASS,
	COLOR_GUARANA,
	COLOR_SOSNOWKIS_BORSCHT,
	COLOR_WOLFBERRIES
};

enum ColorPairs {
	PAIR_ANTELOPE = 16,
	PAIR_CYBER_SHEEP,
	PAIR_FOX,
	PAIR_HUMAN,
	PAIR_SHEEP,
	PAIR_TURTLE,
	PAIR_WOLF,
	PAIR_DANDELION,
	PAIR_GRASS,
	PAIR_GUARANA,
	PAIR_SOSNOWKIS_BORSCHT,
	PAIR_WOLFBERRIES
};
